### ISSUE TITLE
ibus-sunpinyin can't work fine with ibus 1.4.99

### ISSUE THREAD

**Issue by hillwoodroc** [sunpinyin/sunpinyin#13]
The config tool can't be opened .

linux@linux:~> /usr/lib/ibus-sunpinyin/ibus-setup-sunpinyin

*\* (process:4196): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

*\* (process:4196): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

*\* (process:4196): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
Traceback (most recent call last):
  File "/usr/share//ibus-sunpinyin/setup/main.py", line 42, in <module>
    import ibus
ImportError: No module named ibus

**Comment by Windywind** [comment]
# /usr/lib/ibus/ibus-setup-sunpinyin 
Traceback (most recent call last):
  File "/usr/share//ibus-sunpinyin/setup/main.py", line 42, in <module>
    import ibus
ImportError: No module named ibus

Similar things happened to me.

**Comment by lidaobing** [comment]
this issue can be closed
