### ISSUE TITLE
cannot open the preferences window on GNOME

### ISSUE THREAD

**Issue by FranklinYu** [sunpinyin/sunpinyin#136]
Operating system: Debian testing \
GNOME version: 41.3

When I click the icon for SunPinyin preferences in the GNOME Settings, nothing happens.

**Comment by jiru** [comment]
I have the same problem using latest Archlinux (Python 3.11). I can run the preference program directly and it shows an error:
```
$ /usr/lib/ibus-sunpinyin/ibus-setup-sunpinyin

Traceback (most recent call last):
  File "/usr/share//ibus-sunpinyin/setup/main.py", line 627, in <module>
    MainWindow().run()
  File "/usr/share//ibus-sunpinyin/setup/main.py", line 487, in run
    self.__init_ui("main_window")
  File "/usr/share//ibus-sunpinyin/setup/main.py", line 492, in __init_ui
    self.__init_gettext()
  File "/usr/share//ibus-sunpinyin/setup/main.py", line 506, in __init_gettext
    gettext.bind_textdomain_codeset(GETTEXT_PACKAGE, "UTF-8")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'gettext' has no attribute 'bind_textdomain_codeset'
```
This is the same bug as [this one](https://bugs.archlinux.org/task/78388). The proposed solution of commenting out the call to `bind_textdomain_codeset()` worked for me.

**Comment by FranklinYu** [comment]
Thanks for the information. Seems to be this line:

https://github.com/sunpinyin/sunpinyin/blob/6b8db38e26015732975a840eecac63c0035ade2f/wrapper/ibus/setup/main.py#L505-L506

Does `bindtextdomain` do the same thing? If so we can probably removed the `bind_textdomain_codeset` call?

**Comment by wang-yiwei** [comment]
> Thanks for the information. Seems to be this line:
> 
> https://github.com/sunpinyin/sunpinyin/blob/6b8db38e26015732975a840eecac63c0035ade2f/wrapper/ibus/setup/main.py#L505-L506
> 
> Does `bindtextdomain` do the same thing? If so we can probably removed the `bind_textdomain_codeset` call?

`bindtextdomain` was kept since Python 3.10, but it's not recommended to modify the `main.py`. Commenting the corrupted line and configuring the input method via GUI seems to be right, but still suggest uncommenting it after a proper configuration since this outdated line doesn't affect the dconf setting etc.

**Comment by lutingrong** [comment]
> Thanks for the information. Seems to be this line:
> 
> [sunpinyin/wrapper/ibus/setup/main.py](https://github.com/sunpinyin/sunpinyin/blob/6b8db38e26015732975a840eecac63c0035ade2f/wrapper/ibus/setup/main.py#L505-L506)
> 
> Lines 505 to 506 in [6b8db38](/sunpinyin/sunpinyin/commit/6b8db38e26015732975a840eecac63c0035ade2f)
>  gettext.bindtextdomain(GETTEXT_PACKAGE, localedir) 
>  gettext.bind_textdomain_codeset(GETTEXT_PACKAGE, "UTF-8") 
> 
> Does `bindtextdomain` do the same thing? If so we can probably removed the `bind_textdomain_codeset` call?

this workaround can make the preferences window open , but the configuration data lose after restart .
