### ISSUE TITLE
failed to save preferences

### ISSUE THREAD

**Issue by lidaobing** [sunpinyin/sunpinyin#85]
env: 
ubuntu 18.04, 
ibus-sunpinyin version: 2.0.3+git20181120-1
ibus version: 1.5.17-3ubuntu4

open preference, enable "[/]" on pagedown, then Appply, following error happened

```
Traceback (most recent call last):
  File "/usr/share//ibus-sunpinyin/setup/main.py", line 603, in on_main_ok_clicked
    self.__write_config()
  File "/usr/share//ibus-sunpinyin/setup/main.py", line 559, in __write_config
    opt.write_config()
  File "/usr/share//ibus-sunpinyin/setup/main.py", line 118, in write_config
    self.write(v)
  File "/usr/share//ibus-sunpinyin/setup/main.py", line 83, in write
    return self.config.set_value(section, key, type(self.default)(v))
  File "/usr/lib/python3/dist-packages/gi/overrides/IBus.py", line 87, in set_value
    super(Config, self).set_value(section, name, value)
TypeError: argument value: Expected GLib.Variant, but got int
```

**Comment by lidaobing** [comment]
@tchaikov check the PR in #86 , thx
